name: Execution Flow with PR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo " Building the application"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: |
          echo " Running tests"


  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo " Deploying to Production (only on push to main and if tests passed)"
