name: Greeting on variable day

on:
  workflow_dispatch


  

jobs:
  greeting_job:
    runs-on: ubuntu-latest
  
    
    steps:
      - name: "Greetings"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Selva
          DAY_OF_WEEK: sunday
          Greeting: Hello

       
